/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import dialogView from "./script/dialogView"
import gameUI from "./script/gameUI"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/dialogView.js",dialogView);
		reg("script/gameUI.js",gameUI);
    }
}
GameConfig.width = 600;
GameConfig.height = 400;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "center";
GameConfig.startScene = "startScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = true;
GameConfig.stat = true;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
